### ISSUE TITLE
Set-up a remote docker for backend

### ISSUE THREAD

**Issue by Floflobel** [nextcloud/context_chat_backend#3]
Hello,

I tried to set up the whole set-up without having Docker on my Nextcloud. I would like to make a separate docker for the backend.

The problem is that when configuring on Nextcloud in the admin interface we have to specify a docker network.

Is it possible to carry out this installation only by connecting to the backend port and sharing the /var/www/nextcloud folder with the backend?

**Comment by kyteinsky** [comment]
What do you mean by "a separate docker for the backend"? A remote instance with this backend app in a docker container? You will need to provide the NC's web server user access to `/var/run/docker.sock` for AppAPI to work.

During the configuration in NC, you might have seen the AppAPI's deploy daemon settings. The default one prevents access to the external app's port in the whole machine but only inside the docker network and in NC.

Yes, you can totally do that by just having access to the host and port and don't need to provide access to the nextcloud folder to the external app. The [register step](https://github.com/nextcloud/context_chat_backend/blob/master/Makefile#L42-L44) will do just that but would require you to create a manual deploy daemon first.
```sh
occ app_api:daemon:register --net host manual_install "Manual Install" manual-install http null <nextcloud_url>
```
More info here: https://cloud-py-api.github.io/app_api/CreationOfDeployDaemon.html

**Comment by kyteinsky** [comment]
> But from what I understand "context_chat_backend" needs to have access to the Docker socket to work ?

Yes, for the one-click install from the External App Store. For the manual one, the `manual-install` deploy daemon can be used instead.

> Are you talking about performing the Complex Install (without docker) in this case?

Since you're using portainer to manage your docker containers,
1. you can build a docker image from the `Dockerfile.dev` file and remember to tweak the example.env to your liking or mount a volume for the .env file
2. create a docker container and expose the defined port the .env file
3. register a manual-install deploy daemon (see my previous post)
4. register the context_chat_backend app (you can find the command in the Makefile)

You should be able to use Context chat now, provided you installed the php companion `context_chat` app and the `app_api` app. Quick way to test it would be `occ context_chat:scan <username>`

**Comment by bigcat88** [comment]
> Since you're using portainer to manage your docker containers,

Do we really have a difference between Portainer and Docker?
_For AppAPI there is no difference between Portainer or Docker, as they are compatible and both use Docker Engine_

**Comment by kyteinsky** [comment]
> Do we really have a difference between Portainer and Docker?  
> _For AppAPI there is no difference between Portainer or Docker, as they are compatible and both use Docker Engine_

I meant to say that @Floflobel is using docker and does not need to fiddle with the (manual install  without docker) and the dependencies.

**Comment by kyteinsky** [comment]
> I do have one final question. It seems that my "Context Chat Backend" application is in version 1.0.0 and not 1.0.1.

yeah it was just a readme update to the app store so the docker image uses the same 1.0.0 version. It is absolutely fine.

In the Nextcloud GUI, AppAPI reports an error because it cannot contact the docker socket which is required if AppAPI were to setup the docker container for the ex-app itself, which is not the case here so it should be good for this app. If you want to install other external apps through the GUI, that mandates the docker.sock access in the Nextcloud container.

**Comment by kyteinsky** [comment]
Thanks to you for trying out the app! Does it work reliably on your system for general queries? It would be helpful to identify bugs upfront.
